print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/peter/Documents/outdriller/Assets/tunnel001.ma"`)
{		
	file -o "/Users/peter/Documents/outdriller/Assets/tunnel001.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/peter/Documents/outdriller/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/peter/Documents/outdriller/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/peter/Documents/outdriller/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
